cluster_name = "local-cluster"
location = "local-1"
server_id = 1 # the server to connect to
local_deployment = true # use localhost
summary_filepath = "../benchmarks/logs/local-run/client-1.json"
output_filepath = "../benchmarks/logs/local-run/client-1.csv"

# Defining TOML vector of (duration_sec, requests_per_sec, read_ratio) which determines the behavior of the client requests
[request_config]
duration_sec = 40
requests_per_sec = 375
read_ratio = 0.5
key_range = [0, 2999]

[request_config.skew]
 type = "Weighted"
 weights = [5, 3, 2]
# type = "Uniform"
